In [27]:
import pandas as pd
import numpy as np

from ast import literal_eval

# Load dataset

In [28]:
df_movies = pd.read_csv('dataset/raw/tmdb_5000_movies.csv')
df_credits = pd.read_csv('dataset/raw/tmdb_5000_credits.csv')

In [29]:
df_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [30]:
df_credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [31]:
print('df_movies.shape = {}'.format(df_movies.shape))
print('df_credits.shape = {}'.format(df_credits.shape))

df_movies.shape = (4803, 20)
df_credits.shape = (4803, 4)

In [32]:
# Check for null values.
df_movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [33]:
# Check for null values.
df_credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [34]:
df_credits = df_credits.rename(columns={'movie_id': 'id'})

# Merge dataframes
df_data = pd.merge(df_movies, df_credits, on='id')
df_data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [35]:
# Check for null values.
df_data.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title_x                    0
vote_average               0
vote_count                 0
title_y                    0
cast                       0
crew                       0
dtype: int64

In [36]:
df_data.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title_x                  object
vote_average            float64
vote_count                int64
title_y                  object
cast                     object
crew                     object
dtype: object

### Drop some attributes

Since the __homepage__ column has a large of empty values and doesn't has big importance on recommendation system, it can be dropped. The __tagline__ column also can be dropped because the most part of the movies has an overview and thus the tagline would result in redundant data. The __id__ column is unique for each movie, it is only for purpose of identification, thus it will be dropped because it not contribute to the recommendations.

In [37]:
df_data = df_data.drop(columns=['homepage', 'tagline', 'id', 'title_x', 'title_y'])

In [38]:
df_data.isnull().sum()

budget                  0
genres                  0
keywords                0
original_language       0
original_title          0
overview                3
popularity              0
production_companies    0
production_countries    0
release_date            1
revenue                 0
runtime                 2
spoken_languages        0
status                  0
vote_average            0
vote_count              0
cast                    0
crew                    0
dtype: int64

### Drop movies which are unreleased

In [39]:
df_data['status'].value_counts()

Released           4795
Rumored               5
Post Production       3
Name: status, dtype: int64

In [40]:
df_data = df_data.drop(df_data[df_data.status != 'Released'].index)
df_data = df_data.reset_index(drop=True)

### Converts some attributes

Convert the attributes __genres__, __keywords__, __cast__ and __crew__ to list of dictionarys.

In [41]:
columns = ['genres', 'keywords', 'cast', 'crew']
for column in columns:
    df_data[column] = df_data[column].apply(literal_eval)

### Functions

Some functions to extract and manipulate the data.

In [42]:
def get_director_name(list_data):
    for data in list_data:
        if data['job'] == 'Director':
            return data['name']
    return np.nan

def get_list(list_data):
    if isinstance(list_data, list):
        list_names = [data['name'] for data in list_data]
        return list_names
    return []

def standardize_data(obj):
    if isinstance(obj, list):
        return [str.lower(i.replace(' ', '')) for i in obj]
    else:
        if isinstance(obj, str):
            return str.lower(obj.replace(' ', ''))
        else:
            return ''
        
def create_metadata(obj):
    return ' '.join(obj['genres']) + ' ' + ' '.join(obj['keywords']) + ' ' + ' '.join(obj['cast']) + ' ' + obj['director']

In [43]:
# Make a new column with director names.
df_data['director'] = df_data['crew'].apply(get_director_name)

In [44]:
# Convert the columns below to list of names.
columns = ['genres', 'keywords', 'cast']
for column in columns:
    df_data[column] = df_data[column].apply(get_list)

In [45]:
# Convert all strings to lowercase and remove spaces.
columns = ['genres', 'keywords', 'cast', 'director']
for column in columns:
    df_data[column] = df_data[column].apply(standardize_data)

### Generate the metadata

The columns __genres__, __keywords__, __cast__ and __director__ are used to generate the metadata. These metadata will be used to feed the word vector model.

In [46]:
# Generate the metadata that will be fed into the word vector model.
df_data['metadata'] = df_data.apply(create_metadata, axis=1)

In [47]:
df_data[['original_title', 'genres', 'keywords', 'cast', 'director', 'metadata']]

,original_title,genres,keywords,cast,director,metadata
0,Avatar,"[action, adventure, fantasy, sciencefiction]","[cultureclash, future, spacewar, spacecolony, ...","[samworthington, zoesaldana, sigourneyweaver, ...",jamescameron,action adventure fantasy sciencefiction cultur...
1,Pirates of the Caribbean: At World's End,"[adventure, fantasy, action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[johnnydepp, orlandobloom, keiraknightley, ste...",goreverbinski,adventure fantasy action ocean drugabuse exoti...
2,Spectre,"[action, adventure, crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[danielcraig, christophwaltz, lÃ©aseydoux, ralp...",sammendes,action adventure crime spy basedonnovel secret...
3,The Dark Knight Rises,"[action, crime, drama, thriller]","[dccomics, crimefighter, terrorist, secretiden...","[christianbale, michaelcaine, garyoldman, anne...",christophernolan,action crime drama thriller dccomics crimefigh...
4,John Carter,"[action, adventure, sciencefiction]","[basedonnovel, mars, medallion, spacetravel, p...","[taylorkitsch, lynncollins, samanthamorton, wi...",andrewstanton,action adventure sciencefiction basedonnovel m...
...,...,...,...,...,...,...
4790,El Mariachi,"[action, crime, thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...","[carlosgallardo, jaimedehoyos, petermarquardt,...",robertrodriguez,action crime thriller unitedstatesâ€“mexicobarri...
4791,Newlyweds,"[comedy, romance]",[],"[edwardburns, kerrybishÃ©, marshadietlein, cait...",edwardburns,comedy romance edwardburns kerrybishÃ© marshad...
4792,"Signed, Sealed, Delivered","[comedy, drama, romance, tvmovie]","[date, loveatfirstsight, narration, investigat...","[ericmabius, kristinbooth, crystallowe, geoffg...",scottsmith,comedy drama romance tvmovie date loveatfirsts...
4793,Shanghai Calling,[],[],"[danielhenney, elizacoupe, billpaxton, alanruc...",danielhsia,danielhenney elizacoupe billpaxton alanruck ...
4794,My Date with Drew,[documentary],"[obsession, camcorder, crush, dreamgirl]","[drewbarrymore, brianherzlinger, coreyfeldman,...",brianherzlinger,documentary obsession camcorder crush dreamgir...

In [48]:
df_data['metadata'].values[0]

'action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron'

### Save data preprocessed

In [49]:
df_data[['original_title', 'metadata']].to_csv('dataset/preprocessed/movies.csv', index=False)

In [51]:
df = pd.read_csv('dataset/preprocessed/movies.csv')
df

,original_title,metadata
0,Avatar,action adventure fantasy sciencefiction cultur...
1,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,Spectre,action adventure crime spy basedonnovel secret...
3,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,John Carter,action adventure sciencefiction basedonnovel m...
...,...,...
4790,El Mariachi,action crime thriller unitedstatesâ€“mexicobarri...
4791,Newlyweds,comedy romance edwardburns kerrybishÃ© marshad...
4792,"Signed, Sealed, Delivered",comedy drama romance tvmovie date loveatfirsts...
4793,Shanghai Calling,danielhenney elizacoupe billpaxton alanruck ...
4794,My Date with Drew,documentary obsession camcorder crush dreamgir...